### ISSUE TITLE
Convert Protobuf object to Json and back to Object

### ISSUE THREAD

**Issue by deeshank** [improbable-eng/ts-protoc-gen#119] opened 2018-10-11 22:58 UTC
Hi,

I was wondering if one could convert the protobuf object to JSON and reconstruct back to the protobuf object. This was possible for python using Google protobuf library.

Thanks

**Comment by jonny-improbable** [comment] 2018-10-16 13:27
I believe this is a dupe of #9

**Comment by aWeinzierl** [comment] 2018-12-27 17:32
I believe he means JSON as string instead of binary.
Currently, there is only the binary format afaik.

**Comment by aWeinzierl** [comment] 2019-03-27 18:11
*activity*

**Comment by jonny-improbable** [comment] 2019-03-30 07:08
@aWeinzierl do you have a suggestion for how we can move this issue forward?

**Closed** 2019-07-05 07:46 UTC
Labels: wontfix

**Comment by cprovatas** [comment] 2022-01-02 02:15
_*activity*_
