### ISSUE TITLE
Bazel custom rule doesn't generate dependencies (google-protobuf)

### ISSUE THREAD

**Issue by hectim** [improbable-eng/ts-protoc-gen#99] opened 2018-07-19 16:15 UTC
Hey great project and really happy for the bazel support. 

I was using the bazel custom rule to generate ts output for my protos but one of them has a dependency on the google protobuf timestamp proto. I imported it through my workspace with the name @com_google_protobuf, and they export proto_libraries for each of the well_known_protos (including timestamp). This is the proto library I pass to the custom rule:

```
proto_library(
    name = "public_proto",
    srcs = [
        "entities.proto",
    ],
    deps = [
      "@com_google_protobuf//:timestamp_proto",
    ]
)
```

The generated files look correct, but at the top is an import:
```
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
```
The problem is the custom rule never generates this file (probably because its a dep, not a source?). 
It seems that either the custom rule should generate the file or, if it's only generating srcs, then does my project need to copy the google-protobuf protos in?

**Comment by jonny-improbable** [comment] 2018-07-19 16:34
Thanks for raising, this sounds like a duplicate of #87 (in particular the comment added by @alexanvl here) - could you confirm?

My current thinking is that the `ts-protoc-gen` library should only print import statements if the imported module is actually referenced by the generated output (ie: dead code elimination, similar in vein to the [eslint no-unused-vars rule](https://eslint.org/docs/rules/no-unused-vars)).

**Comment by coltonmorris** [comment] 2018-07-19 17:57
I think this issue is slightly different. The import statement is wanted here, but it's missing the file; where it seems like #87 just want's to remove the import statement.

**Comment by hectim** [comment] 2018-07-19 18:37
Ah I see, yes they are similar in that they are both issues with google-protobuf imports. Like @coltonmorris said #87 wants to remove the annotation import. As far as I can tell that import can always be removed since it's always an unused variable in typescript. In fact the custom rule already has a way to remove unwanted imports for that exact use-case. 
```
    remove_dependencies = [
        "google_api_annotations_pb",
    ],
```

My problem, on the other hand, is I want the imports for timestamp because I actually use it in my messages (unlike annotations), but I also want typescript output for it (which isn't currently generated).  I'm looking into the custom rule, going to see if I can just generate it from the deps and then submit a PR. 

Adding special cases for google-protobuf imports seems bad, but I'm not sure how to tell which ones are important and which aren't.

**Comment by jonnyreeves** [comment] 2018-07-19 19:00
Thanks for confirming, I'm afraid I'm not going to be much help on identifying the solution to this as I have zero working bazel knowledge, but I am happy to help sheppard a change through review 😀

**Comment by coltonmorris** [comment] 2018-10-17 18:31
`npm install --save google-protobuf`

**Closed** 2018-10-17 18:31 UTC
